name: CI - Docker Build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run unit test
      run: npm test

    - name: Run linter
      run: npm run lint 

    - name: Generate code coverage
      run: npm run test -- --coverage

    - name: Build Docker image
      run: docker build -t hi-app .
